services:
  drawio:
    container_name: drawio
    build: ./compose
    restart: always
    env_file:
      - .env
    ports:
      - "8888:80"
    volumes:
      - "./src:/var/www/html"
      - "./compose/nginx.conf:/etc/nginx/nginx.conf"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.drawio.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.drawio.entrypoints=websecure"
      - "traefik.http.routers.drawio.tls.certresolver=myresolver"
    networks:
      web:
networks:
  web:
    name: web
    external: true
